<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'MaddHatter\\LaravelFullcalendar' => array($vendorDir . '/maddhatter/laravel-fullcalendar/src'),
    'Jenssegers\\Mongodb' => array($vendorDir . '/jenssegers/mongodb/src'),
    'ICal' => array($vendorDir . '/johngrogg/ics-parser/src'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Google_' => array($vendorDir . '/google/apiclient/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
);
